
"use client";

import { ThemeProvider } from "@/components/theme-provider";
import { FirebaseClientProvider } from "@/firebase";
import { UserProvider } from "@/context/user-context";
import { Toaster } from "@/components/ui/toaster";
import { ForegroundMessageListener } from "@/lib/firebase/messaging";
import { useEffect } from "react";

// This is the new Client Component that wraps all providers and client-side hooks.
export function AppProviders({ children }: { children: React.ReactNode }) {
  
  useEffect(() => {
    // This effect ensures the PWA service worker (for offline caching) is registered.
    if (
      typeof window !== 'undefined' &&
      'serviceWorker' in navigator &&
      (window as any).workbox !== undefined
    ) {
      const wb = (window as any).workbox;

      wb.addEventListener('waiting', () => {
        // This event fires when a new version of the service worker is waiting to be activated.
        // We can prompt the user to update. By sending `skipWaiting`, the new worker activates immediately.
        console.log('[PWA] A new version is available. Activating...');
        wb.messageSkipWaiting();
      });

      wb.addEventListener('controlling', () => {
        // This event fires when the new service worker has taken control.
        // We can now safely reload the page to use the new assets.
        console.log('[PWA] New service worker has taken control. Reloading page.');
        window.location.reload();
      });
      
      // Registers the PWA service worker (`sw.js`) generated by next-pwa.
      wb.register();
      console.log('[PWA] Service worker registered by workbox.');
    }
  }, []);

  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <FirebaseClientProvider>
        <UserProvider>
          {children}
          <ForegroundMessageListener />
          <Toaster />
        </UserProvider>
      </FirebaseClientProvider>
    </ThemeProvider>
  );
}
